name: "[Story]"
description: Yêu cầu tính năng từ góc nhìn người dùng
labels: ["type:story", "type:devtask"]
body:
  - type: textarea
    id: user_story
    attributes:
      label: 👤 User Story
      description: "Là một người dùng, tôi muốn làm ... để ... ."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: "Với bối cảnh ..., khi làm ..., thì ..."
      value: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: design
    attributes:
      label: 🎨 Design
      description: "Link Figma / mockup"
      value: "-"

  - type: textarea
    id: subtasks
    attributes:
      label: 🔗 Sub-tasks
      value: |
        - [ ] #
        - [ ] #
